In [1]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv("../_data/processed/modeling_dataset.csv")
df.head()

,Customer_ID,total_transactions,total_quantity,total_revenue,avg_order_value,first_purchase,last_purchase,customer_lifetime_days,recency_days,churn
0,12346.0,12,74285,77556.46,2281.072353,2009-12-14 08:34:00,2011-01-18 10:01:00,400,325,1
1,12347.0,8,3286,5633.32,22.266087,2010-10-31 14:20:00,2011-12-07 15:52:00,402,1,0
2,12348.0,5,2714,2019.40,39.596078,2010-09-27 14:59:00,2011-09-25 13:13:00,362,74,0
3,12349.0,4,1624,4428.69,25.306800,2010-04-29 13:20:00,2011-11-21 09:51:00,570,18,0
4,12350.0,1,197,334.40,19.670588,2011-02-02 16:01:00,2011-02-02 16:01:00,0,309,1

In [7]:
df["total_revenue_log"] = np.log1p(df["total_revenue"])
df["avg_order_value_log"] = np.log1p(df["avg_order_value"])
df["total_quantity_log"] = np.log1p(df["total_quantity"])
df["total_transactions_log"] = np.log1p(df["total_transactions"])

In [6]:
df.columns

Index(['Customer_ID', 'total_transactions', 'total_quantity', 'total_revenue',
       'avg_order_value', 'customer_lifetime_days', 'churn'],
      dtype='object')

In [8]:
df = df.drop(
    columns=[
        "total_revenue",
        "avg_order_value",
        "total_quantity",
        "total_transactions"
    ]
)

In [9]:
df["customer_lifetime_days_log"] = np.log1p(df["customer_lifetime_days"])
df = df.drop(columns=["customer_lifetime_days"])

In [10]:
df = df.drop(columns=["Customer_ID"])

In [11]:
df.info()
df.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5878 entries, 0 to 5877
Data columns (total 6 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   churn                       5878 non-null   int64
 1   total_revenue_log           5878 non-null   float64
 2   avg_order_value_log         5878 non-null   float64
 3   total_quantity_log          5878 non-null   float64
 4   total_transactions_log      5878 non-null   float64
 5   customer_lifetime_days_log  5878 non-null   float64
dtypes: float64(5), int64(1)
memory usage: 275.7 KB

,churn,total_revenue_log,avg_order_value_log,total_quantity_log,total_transactions_log,customer_lifetime_days_log
0,1,11.258774,7.732839,11.215678,2.564949,5.993961
1,0,8.636632,3.146997,8.097731,2.197225,5.998937
2,0,7.611051,3.703671,7.906547,1.791759,5.894403
3,0,8.396085,3.269827,7.393263,1.609438,6.347389
4,1,5.815324,3.028712,5.288267,0.693147,0.000000

In [13]:
df.to_csv(
    "../_data/processed/final_features.csv",
    index=False
)